# Netlify Configuration
[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    cache-control = "max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    cache-control = "max-age=31536000"